import { strict as assert } from "node:assert";
import { createProductionEvidenceSyncPackage, productionAcceptanceCheckKeys, sha256, validateProductionEvidenceSyncPackage } from "../src/production-evidence-core";

let cases = 0;
function test(name: string, operation: () => void) { try { operation(); cases += 1; } catch (error) { throw new Error(`${name}: ${error instanceof Error ? error.message : String(error)}`, { cause: error }); } }
const projectId = "lip-knots-production"; const releaseId = "v5.6.0"; const deploymentPlanFingerprint = "a".repeat(64); const acceptancePlanFingerprint = "b".repeat(64); const rollbackPlanFingerprint = "c".repeat(64); const completedAt = "2026-07-14T06:00:00.000Z";
const seal = <T extends Record<string, unknown>>(value: T) => { const base = Object.fromEntries(Object.entries(value).filter(([key]) => key !== "fingerprint")); return { ...base, fingerprint: sha256(base) }; };
const deployment = seal({ schemaVersion: 1, releaseId, projectId, planFingerprint: deploymentPlanFingerprint, approvedByEmail: "executive@lipknots.test", changeTicketId: "REL-400", status: "succeeded", startedAt: "2026-07-14T05:58:00.000Z", completedAt, failedStageKey: null, message: "ok", results: ["project_access", "rules_and_storage", "functions", "hosting", "functions_inventory", "hosting_inventory", "staff_https", "admin_https"].map((key) => ({ key, code: 0 })) });
function run(observedAt: string, passed = true, sourceKind: "deployment"|"rollback" = "deployment", sourceReleaseId = releaseId, sourcePlan = deploymentPlanFingerprint) { const checks = productionAcceptanceCheckKeys.map((key, index) => ({ key, label: key, passed: passed || index > 0, actual: "ok", evidence: { code: passed || index > 0 ? 0 : 1 } })); return seal({ schemaVersion: 1, releaseId: sourceReleaseId, projectId, acceptancePlanFingerprint, deploymentPlanFingerprint: sourcePlan, deploymentCompletedAt: completedAt, sourceKind, observedAt, passed: checks.every((item) => item.passed), checks }); }
function ledger(runs: Array<Record<string, unknown>>, sourceReleaseId = releaseId, sourcePlan = deploymentPlanFingerprint) { const failure = runs.find((item) => item.passed !== true); const spaced: Array<Record<string, unknown>> = []; for (const item of runs.filter((entry) => entry.passed === true)) { const prior = spaced.at(-1); if (!prior || Date.parse(String(item.observedAt)) - Date.parse(String(prior.observedAt)) >= 300_000) spaced.push(item); } const status = failure ? "rollback_required" : spaced.length >= 3 ? "accepted" : "observing"; const failedCheckKeys = failure ? (failure.checks as Array<Record<string, unknown>>).filter((item) => !item.passed).map((item) => item.key) : []; const nextEligibleAt = status === "observing" ? new Date(Date.parse(String(spaced.at(-1)?.observedAt ?? runs.at(-1)?.observedAt)) + 300_000).toISOString() : null; return seal({ schemaVersion: 1, releaseId: sourceReleaseId, projectId, deploymentPlanFingerprint: sourcePlan, acceptancePlanFingerprint, status, requiredPasses: 3, validPasses: spaced.length, nextEligibleAt, failedCheckKeys, runs }); }
const acceptanceObserving = ledger([run("2026-07-14T06:01:00.000Z")]);
const acceptanceAccepted = ledger([run("2026-07-14T06:01:00.000Z"), run("2026-07-14T06:06:00.000Z"), run("2026-07-14T06:11:00.000Z")]);
const acceptanceFailed = ledger([run("2026-07-14T06:01:00.000Z", false)]);
const rollback = seal({ schemaVersion: 1, releaseId, knownGoodReleaseId: "v5.1.0", projectId, rollbackPlanFingerprint, acceptanceLedgerFingerprint: acceptanceFailed.fingerprint, status: "rollback_succeeded", startedAt: "2026-07-14T06:03:00.000Z", completedAt: "2026-07-14T06:08:00.000Z", failedStageKey: null, results: ["project_access", "known_good_rules", "known_good_functions", "staff_hosting_clone", "admin_hosting_clone", "functions_inventory", "hosting_inventory", "staff_https", "admin_https"].map((key) => ({ key, code: 0 })) });
const recoveryObserving = ledger([run("2026-07-14T06:09:00.000Z", true, "rollback", "v5.1.0", rollbackPlanFingerprint)], "v5.1.0", rollbackPlanFingerprint);
const recoveryAccepted = ledger([run("2026-07-14T06:09:00.000Z", true, "rollback", "v5.1.0", rollbackPlanFingerprint), run("2026-07-14T06:14:00.000Z", true, "rollback", "v5.1.0", rollbackPlanFingerprint), run("2026-07-14T06:19:00.000Z", true, "rollback", "v5.1.0", rollbackPlanFingerprint)], "v5.1.0", rollbackPlanFingerprint);
const packageCreatedAt = new Date(Date.now() - 60_000).toISOString();
function pkg(evidence: Record<string, unknown>) { return createProductionEvidenceSyncPackage(evidence, packageCreatedAt); }
function validate(evidence: Record<string, unknown>) { return validateProductionEvidenceSyncPackage(pkg(evidence), { expectedProjectId: projectId }); }

test("deployment package", () => { const value = validate({ deploymentResult: deployment }); assert.equal(value.valid, true); assert.equal(value.summary?.phase, "deployed"); });
test("acceptance observing", () => assert.equal(validate({ deploymentResult: deployment, acceptanceLedger: acceptanceObserving }).summary?.phase, "acceptance_observing"));
test("acceptance accepted", () => { const value = validate({ deploymentResult: deployment, acceptanceLedger: acceptanceAccepted }); assert.equal(value.summary?.phase, "accepted"); assert.equal(value.summary?.acceptance?.validPasses, 3); });
test("rollback required", () => { const value = validate({ deploymentResult: deployment, acceptanceLedger: acceptanceFailed }); assert.equal(value.summary?.phase, "rollback_required"); assert.deepEqual(value.summary?.acceptance?.failedCheckKeys, ["project_access"]); });
test("rollback succeeded", () => assert.equal(validate({ deploymentResult: deployment, acceptanceLedger: acceptanceFailed, rollbackResult: rollback }).summary?.phase, "rollback_succeeded"));
test("recovery observing", () => assert.equal(validate({ deploymentResult: deployment, acceptanceLedger: acceptanceFailed, rollbackResult: rollback, recoveryAcceptanceLedger: recoveryObserving }).summary?.phase, "recovery_observing"));
test("recovered", () => { const value = validate({ deploymentResult: deployment, acceptanceLedger: acceptanceFailed, rollbackResult: rollback, recoveryAcceptanceLedger: recoveryAccepted }); assert.equal(value.summary?.phase, "recovered"); assert.equal(value.summary?.progressScore, 900); });
test("deterministic package", () => assert.equal(pkg({ deploymentResult: deployment }).fingerprint, pkg({ deploymentResult: deployment }).fingerprint));
test("timeline", () => assert.deepEqual(validate({ deploymentResult: deployment, acceptanceLedger: acceptanceAccepted }).summary?.timeline.map((item) => item.status), ["passed", "passed", "waiting", "waiting"]));

const rejectCases: Array<[string, (value: any) => void]> = [
  ["package schema", (value) => { value.schemaVersion = 2; }], ["package release", (value) => { value.releaseId = "v3.9.0"; }], ["package project", (value) => { value.projectId = "other-production"; }], ["package fingerprint", (value) => { value.fingerprint = "d".repeat(64); }], ["package future", (value) => { value.createdAt = new Date(Date.now() + 600_000).toISOString(); resealPackage(value); }],
  ["deployment status", (value) => { value.evidence.deploymentResult.status = "failed"; resealEvidence(value, "deploymentResult"); }], ["deployment result", (value) => { value.evidence.deploymentResult.results[2].code = 1; resealEvidence(value, "deploymentResult"); }], ["deployment email", (value) => { value.evidence.deploymentResult.approvedByEmail = "bad"; resealEvidence(value, "deploymentResult"); }], ["deployment time", (value) => { value.evidence.deploymentResult.completedAt = "2026-07-14T05:00:00Z"; resealEvidence(value, "deploymentResult"); }], ["deployment fingerprint", (value) => { value.evidence.deploymentResult.fingerprint = "e".repeat(64); resealPackage(value); }],
  ["deployment duplicate result", (value) => { value.evidence.deploymentResult.results[7] = value.evidence.deploymentResult.results[6]; resealEvidence(value, "deploymentResult"); }], ["deployment extra result", (value) => { value.evidence.deploymentResult.results.push({ key: "unknown", code: 0 }); resealEvidence(value, "deploymentResult"); }],
  ["acceptance chain", (value) => { value.evidence.acceptanceLedger.deploymentPlanFingerprint = "f".repeat(64); resealEvidence(value, "acceptanceLedger"); }], ["acceptance fingerprint", (value) => { value.evidence.acceptanceLedger.fingerprint = "f".repeat(64); resealPackage(value); }], ["acceptance state", (value) => { value.evidence.acceptanceLedger.status = "accepted"; resealEvidence(value, "acceptanceLedger"); }], ["acceptance passes", (value) => { value.evidence.acceptanceLedger.validPasses = 3; resealEvidence(value, "acceptanceLedger"); }], ["acceptance check inventory", (value) => { value.evidence.acceptanceLedger.runs[0].checks.pop(); resealRunAndLedger(value.evidence.acceptanceLedger, 0); resealPackage(value); }], ["acceptance run state", (value) => { value.evidence.acceptanceLedger.runs[0].passed = false; resealRunAndLedger(value.evidence.acceptanceLedger, 0); resealPackage(value); }], ["acceptance run time", (value) => { value.evidence.acceptanceLedger.runs[0].observedAt = "2026-07-14T07:00:00Z"; resealRunAndLedger(value.evidence.acceptanceLedger, 0); resealPackage(value); }],
];
for (const [name, mutate] of rejectCases) test(`reject ${name}`, () => { const value: any = structuredClone(pkg({ deploymentResult: deployment, acceptanceLedger: acceptanceObserving })); mutate(value); assert.equal(validateProductionEvidenceSyncPackage(value, { expectedProjectId: projectId }).valid, false); });
test("reject rollback without failure", () => assert.equal(validate({ deploymentResult: deployment, acceptanceLedger: acceptanceAccepted, rollbackResult: rollback }).valid, false));
test("reject rollback chain", () => { const value: any = structuredClone(rollback); value.acceptanceLedgerFingerprint = "f".repeat(64); Object.assign(value, seal(value)); assert.equal(validate({ deploymentResult: deployment, acceptanceLedger: acceptanceFailed, rollbackResult: value }).valid, false); });
test("reject rollback failed result", () => { const value: any = structuredClone(rollback); value.results[2].code = 1; Object.assign(value, seal(value)); assert.equal(validate({ deploymentResult: deployment, acceptanceLedger: acceptanceFailed, rollbackResult: value }).valid, false); });
test("reject recovery without rollback", () => assert.equal(validate({ deploymentResult: deployment, acceptanceLedger: acceptanceFailed, recoveryAcceptanceLedger: recoveryAccepted }).valid, false));
test("reject recovery chain", () => { const value: any = structuredClone(recoveryAccepted); value.deploymentPlanFingerprint = "f".repeat(64); Object.assign(value, seal(value)); assert.equal(validate({ deploymentResult: deployment, acceptanceLedger: acceptanceFailed, rollbackResult: rollback, recoveryAcceptanceLedger: value }).valid, false); });
test("reject secret", () => { const value: any = structuredClone(deployment); value.results[0].stderr = "Bearer abcdefghijklmnopqrstuvwxyz"; Object.assign(value, seal(value)); assert.equal(validate({ deploymentResult: value }).valid, false); });
console.log(`production evidence live sync tests passed (${cases} cases)`);

function resealPackage(value: any) { const base = Object.fromEntries(Object.entries(value).filter(([key]) => key !== "fingerprint")); value.fingerprint = sha256(base); }
function resealEvidence(value: any, key: string) { value.evidence[key] = seal(value.evidence[key]); resealPackage(value); }
function resealRunAndLedger(value: any, index: number) { value.runs[index] = seal(value.runs[index]); Object.assign(value, seal(value)); }
